#!/usr/bin/env bash


ERROR_MSG=

EXECUTABLES=(
	work_queue_status      # check cctools installation
	pdb2gmx grompp mdrun   # check gromacs installation
)

PYMODS=(work_queue numpy prody trax awe)


fail() {
	ERROR_MSG="$@"
	return 0
}


die() {
	echo "$ERROR_MSG"
	exit $1
}


check-exe() {
	local name=$1
	which $name >/dev/null 2>&1
}

check-pymodule() {
	local name=$1
	python -c "import $name" >/dev/null 2>&1
}


for n in ${EXECUTABLES[@]}; do
	printf "Checking for executable $n..."
	(check-exe $n && echo OK) || echo FAIL

done

for n in ${PYMODS[@]}; do
	printf "Checking for python module $n..."
	(check-pymodule $n && echo OK) || echo FAIL
done
