#!/usr/bin/env bash

EXITCODE=0


ACCEPTABLE_PYTHON_VERSION=(2.6 2.7)

EXECUTABLES=(
	work_queue_status      # check cctools installation
	pdb2gmx grompp mdrun   # check gromacs installation
	awe-assign
)

PYMODS=(work_queue numpy prody trax awe)



get-python-version() {
	python -c 'import sys;v=sys.version_info;major=v[0];minor=v[1];print "%s.%s" % (major,minor)'
}

check-python-version() {
	pv=$(get-python-version)
	for v in ${ACCEPTABLE_PYTHON_VERSION[@]}; do
		test  $pv == $v && return 0
	done
	return 1
}

check-exe() {
	local name=$1
	which $name >/dev/null 2>&1
}

check-pymodule() {
	local name=$1
	python -c "import $name" >/dev/null 2>&1
}



printf "Checking for compatible python..."
(check-python-version && echo OK) || echo "FAIL: found $(get-python-version) is not one of ${ACCEPTABLE_PYTHON_VERSION[@]}"

for n in ${EXECUTABLES[@]}; do
	printf "Checking for executable $n..."
	if check-exe $n; then
		echo OK
	else
		echo FAIL
		EXITCODE=1
	fi
done

for n in ${PYMODS[@]}; do
	printf "Checking for python module $n..."
	if check-pymodule $n; then
		echo OK
	else
		echo FAIL
		EXITCODE=1
	fi
done

exit $EXITCODE
