#!/afs/crc.nd.edu/user/j/jkinniso/Public/apps/x86_64/anaconda/bin/python
"""
Short script for calculating 
"""

import sys
import argparse

import numpy as np
import matplotlib.pyplot as plt

def parse_args(args):
    description = """
A utility script for plotting implied timescales in MSMBuilder preprocessing.
    """
    
    parser = argparse.ArgumentParser(description=description)
    
    parser.add_argument("-i", "--input",
        default="ImpliedTimescales.dat",
        type=str,
        help="file containing implied timescales"
    )
    
    parser.add_argument("--title",
        default="",
        type=str,
        help="title of the plot"
    )
  
    parser.add_argument("--yscale",
        default="log",
        type=str,
        help="the scale of the y-axis"
    )
    
    parser.add_argument("--xlabel",
        default="Lag Time",
        type=str,
        help="x-axis label"
    )
    
    parser.add_argument("--ylabel",
        default="Implied Timescale",
        type=str,
        help="y-axis label"
    )
    
    return parser.parse_args()

if __name__ == "__main__":
    opts = parse_args(sys.argv)
    ts = np.loadtxt(opts.input)
    plt.scatter(ts[:,0], ts[:,1])
    plt.yscale(opts.yscale)
    plt.title(opts.title)
    plt.xlabel(opts.xlabel)
    plt.ylabel(opts.ylabel)
    plt.show()